# Generated by Django 2.0.2 on 2020-05-25 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='imgage',
            new_name='imagen',
        ),
    ]
